In [15]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [16]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [17]:
print(x)

[['Italy' 40.0 74000.0]
 ['Denmark' 25.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Denmark' nan 61000.0]
 ['Germany' 35.0 73000.0]
 ['Italy' 45.0 58000.0]
 ['Denmark' 32.0 75000.0]
 ['Italy' 50.0 71000.0]
 ['Germany' 27.0 nan]
 ['Italy' 48.0 67000.0]]


In [18]:
print(y)

['Yes' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [19]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [20]:
print(x)

[['Italy' 40.0 74000.0]
 ['Denmark' 25.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Denmark' 36.888888888888886 61000.0]
 ['Germany' 35.0 73000.0]
 ['Italy' 45.0 58000.0]
 ['Denmark' 32.0 75000.0]
 ['Italy' 50.0 71000.0]
 ['Germany' 27.0 64555.555555555555]
 ['Italy' 48.0 67000.0]]


In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [23]:
print(x)

[[0.0 0.0 1.0 40.0 74000.0]
 [1.0 0.0 0.0 25.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 36.888888888888886 61000.0]
 [0.0 1.0 0.0 35.0 73000.0]
 [0.0 0.0 1.0 45.0 58000.0]
 [1.0 0.0 0.0 32.0 75000.0]
 [0.0 0.0 1.0 50.0 71000.0]
 [0.0 1.0 0.0 27.0 64555.555555555555]
 [0.0 0.0 1.0 48.0 67000.0]]


In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [25]:
print(y)

[1 0 0 1 1 1 0 1 0 1]


In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [27]:
print(x_train)

[[1.0 0.0 0.0 32.0 75000.0]
 [0.0 1.0 0.0 35.0 73000.0]
 [0.0 0.0 1.0 40.0 74000.0]
 [1.0 0.0 0.0 36.888888888888886 61000.0]
 [1.0 0.0 0.0 25.0 48000.0]
 [0.0 0.0 1.0 50.0 71000.0]
 [0.0 1.0 0.0 27.0 64555.555555555555]
 [0.0 0.0 1.0 45.0 58000.0]]


In [28]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 48.0 67000.0]]


In [29]:
print(y_train)

[0 1 1 1 0 1 0 1]


In [30]:
print(y_test)

[0 1]


In [34]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [35]:
print(x_train)

[[1.0 0.0 0.0 -0.5452736725017974 1.0605142590617367]
 [0.0 1.0 0.0 -0.1701809551120259 0.8356040185537982]
 [0.0 0.0 1.0 0.4549735738709266 0.9480591388077674]
 [1.0 0.0 0.0 0.06598853361486687 -0.5138574244938312]
 [1.0 0.0 0.0 -1.420490013077931 -1.9757739877954295]
 [0.0 0.0 1.0 1.7052826318368315 0.61069377804586]
 [0.0 1.0 0.0 -1.1704282014847498 -0.11401699692416324]
 [0.0 0.0 1.0 1.0801281028538792 -0.8512227852557385]]


In [36]:
print(x_test)

[[0.0 1.0 0.0 -0.9999999999999996 -1.0000000000000009]
 [0.0 0.0 1.0 1.0000000000000004 0.9999999999999993]]
